### ISSUE TITLE
[suggestion] update

### ISSUE THREAD

**Issue by ghost** [jenskutilek/free-fonts#1]
updated two months ago with new glyphs..
<a href="https://github.com/google/fonts/tree/master/apache/opensans/">https://github.com/google/fonts/tree/master/apache/opensans/</a>
<a href="https://github.com/google/fonts/tree/master/apache/opensanscondensed/">https://github.com/google/fonts/tree/master/apache/opensanscondensed/</a>
<a href="https://github.com/google/fonts/tree/master/apache/opensanshebrew/">https://github.com/google/fonts/tree/master/apache/opensanshebrew/</a>
<a href="https://github.com/google/fonts/tree/master/apache/opensanshebrewcondensed/">https://github.com/google/fonts/tree/master/apache/opensanshebrewcondensed/</a>

although it does not contain the superior OTF variation, just the TTF :[

**Comment by jenskutilek** [comment]
I couldn’t find any new glyphs, but I updated the files anyway. Thanks!
