### ISSUE TITLE
Droid Sans Fallback is always corrupted file after download

### ISSUE THREAD

**Issue by doneykoo** [jenskutilek/free-fonts#2]
Droid Sans Fallback
free-fonts/Droid/Droid Sans Fallback/DroidSansFallback.ttf

The file is always corrupted file after download.
(Windows 10, Firefox 59)

**Comment by jenskutilek** [comment]
Droid Sans Fallback seems to be a special fallback font that is only intended to work in a specific environment. It does not contain a lot of compatibility information that is expected by other systems, so it may be reported as invalid. I think this is the intended behaviour.
